data:extend {
  {
    type = "optimized-particle",
    name = "tin-ore-particle",
    flags = {"not-on-map"},
    life_time = 180,
    pictures = {
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-1.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-2.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-3.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-4.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
    },
    shadows = {
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-shadow-1.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-shadow-2.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-shadow-3.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
      {
          filename = "__khaostin__/graphics/entity/tin-ore-particle/tin-ore-particle-shadow-4.png",
          priority = "extra-high",
          width = 32,
          height = 32,
          frame_count = 1,
          scale = 0.5,
      },
    },
  },
}
